mariadb:
  enabled: false
postgresql:
  enabled: false
externalDatabase:
  host: scdf-postgresql
  port: 5432
  scheme: postgresql
  driver: org.postgresql.Driver
  dataflow:
    database: scdf-db
    username: user
    password: bitnami
  skipper:
    database: scdf-db
    username: user
    password: bitnami
rabbitmq:
  enabled: true
  auth:
    username: user
    password: bitnami
  service:
    type: NodePort
    nodePorts:
      amqp: 30672
      manager: 31672
