skipper:
  extraEnvVars:
    - name: MAVEN_LOCAL_REPOSITORY
      value: "/dataflow-maven-repo/.m2/repository"
    - name: JAVA_OPTS
      value: "-Duser.home=/dataflow-maven-repo"
  extraVolumeMounts:
    - name: maven-repo
      mountPath: /dataflow-maven-repo
  extraVolumes:
    - name: maven-repo
      emptyDir: {}
server:
  extraEnvVars:
    - name: MAVEN_LOCAL_REPOSITORY
      value: "/dataflow-maven-repo/.m2/repository"
    - name: JAVA_OPTS
      value: "-Duser.home=/dataflow-maven-repo"
  extraVolumeMounts:
    - name: maven-repo
      mountPath: /dataflow-maven-repo
  extraVolumes:
    - name: maven-repo
      emptyDir: {}
mariadb:
  enabled: false
postgresql:
  enabled: false
externalDatabase:
  host: scdf-postgresql
  port: 5432
  scheme: postgresql
  driver: org.postgresql.Driver
  dataflow:
    database: scdf-db
    username: user
    password: bitnami
  skipper:
    database: scdf-db
    username: user
    password: bitnami
rabbitmq:
  enabled: true
  auth:
    username: user
    password: bitnami
  service:
    type: NodePort
    nodePorts:
      amqp: 30672
      manager: 31672
networkPolicy:
  enabled: false
