skipper:
  extraEnvVars:
    - name: MAVEN_LOCAL_REPOSITORY
      value: "/dataflow-maven-repo/.m2/repository"
    - name: JAVA_OPTS
      value: "-Duser.home=/dataflow-maven-repo"
    - name: SPRING_CLOUD_SKIPPER_MAVEN_REMOTE_REPOSITORIES_REPO1_URL
      value: "https://repo.maven.apache.org/maven2"
  extraVolumeMounts:
    - name: maven-repo
      mountPath: "/dataflow-maven-repo"
  extraVolumes:
    - name: maven-repo
      emptyDir: {}
  service:
    type: NodePort
    nodePort: 30081
  deployer:
    kubernetes:
      environmentVariables:
        - name: MAVEN_REMOTE_REPOSITORIES
          value: "https://repo.maven.apache.org/maven2"
        - name: MAVEN_LOCAL_REPOSITORY
          value: "/dataflow-maven-repo/.m2/repository"
      volumeMounts:
        - name: maven-repo
          mountPath: "/dataflow-maven-repo"
server:
  extraEnvVars:
    - name: MAVEN_LOCAL_REPOSITORY
      value: "/dataflow-maven-repo/.m2/repository"
    - name: JAVA_OPTS
      value: "-Duser.home=/dataflow-maven-repo"
    - name: SPRING_CLOUD_DATAFLOW_SERVER_MAVEN_REMOTE_REPOSITORIES_REPO1_URL
      value: "https://repo.maven.apache.org/maven2"
  extraVolumeMounts:
    - name: maven-repo
      mountPath: "/dataflow-maven-repo"
  extraVolumes:
    - name: maven-repo
      emptyDir: {}
  deployer:
    kubernetes:
      environmentVariables:
        - name: MAVEN_REMOTE_REPOSITORIES
          value: "https://repo.maven.apache.org/maven2"
        - name: MAVEN_LOCAL_REPOSITORY
          value: "/dataflow-maven-repo/.m2/repository"
      volumeMounts:
        - name: maven-repo
          mountPath: "/dataflow-maven-repo"
mariadb:
  enabled: false
postgresql:
  enabled: false
externalDatabase:
  host: scdf-postgresql
  port: 5432
  scheme: postgresql
  driver: org.postgresql.Driver
  dataflow:
    database: scdf-db
    username: user
    password: bitnami
  skipper:
    database: scdf-db
    username: user
    password: bitnami
rabbitmq:
  enabled: true
  auth:
    username: user
    password: bitnami
  service:
    type: NodePort
    nodePorts:
      amqp: 30672
      manager: 31672
networkPolicy:
  enabled: false
