# ------------------------------------------------------------------------------
# MinIO PersistentVolume and PersistentVolumeClaim for Static hostPath Storage
# ------------------------------------------------------------------------------
# This YAML defines a static PersistentVolume and PersistentVolumeClaim for MinIO.
# The PV uses hostPath mapped to /Users/dbbaskette/Projects/SCDF-RAG/sourceDocs.
# The PVC binds directly to the PV by name and StorageClass.
#
# Requirements:
#   - Directory /Users/dbbaskette/Projects/SCDF-RAG/sourceDocs must exist on the host
#   - Used with minio_install_scdf.sh script
# ------------------------------------------------------------------------------
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/dbbaskette/Projects/SCDF-RAG/sourceDocs
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: scdf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: minio-pv
#  storageClassName: hostpath (removed for static binding)
